# Generated by Django 3.0.3 on 2020-04-10 22:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicalmeasures',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('txid', models.BigIntegerField()),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField()),
                ('resource_type', models.TextField(blank=True, null=True)),
                ('resource', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'codesystem',
                'managed': False,
            },
        ),
    ]
