# Generated by Django 3.0.3 on 2020-04-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0002_clinicalmeasures'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinicalmeasures',
            table='clinicalmeasures',
        ),
    ]
